spring:
  datasource:
    url: "jdbc:mysql://0.0.0.0:3306/customer_product_service?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: "test"
    password: "testpw"
    hikari:
      maximumPoolSize: 5
