spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      naming:
        # allow camelCase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate # validate
      # for default naming strategy see: https://stackoverflow.com/questions/25283198/spring-boot-jpa-column-name-annotation-ignored/38875123#38875123
      # https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#naming
  datasource:
    url: "jdbc:mariadb://localhost:3306/jellix?useSSL=false"
    username: root
    password:
    hikari:
      maximumPoolSize: 5
  liquibase:
    change-log: classpath:liquibase/master.xml
